In [1]:
import numpy as np

Create a one-dimensional array (vector) with the first 10 positive integers and display its value.

In [2]:
a1 = np.arange(1, 11, dtype=int)

In [3]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a two-dimensional array (matrix) of size 3x3, fill it with zeros, and display its value.

In [4]:
a2 = np.zeros((3, 3), dtype=int)

In [5]:
a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Create a 5x5 array, fill it with random integers from 1 to 10, and display its value.

In [6]:
a3 = np.random.randint(1, 11, (5, 5))

In [7]:
a3

array([[ 4,  7,  2,  6,  1],
       [ 5,  5,  3,  8,  9],
       [ 1,  4, 10,  2,  6],
       [ 4,  8,  4,  3,  4],
       [10,  2, 10,  8,  4]])

Create a 4x4 array, fill it with random real numbers from 0 to 1, and display its value.

In [8]:
a4 = np.random.random((4, 4))

In [9]:
a4

array([[0.78016382, 0.71237476, 0.48211329, 0.06248218],
       [0.94903721, 0.04034295, 0.05943836, 0.84120469],
       [0.92093814, 0.90128279, 0.45459092, 0.1839803 ],
       [0.20016328, 0.40962307, 0.25123714, 0.16735987]])

Create two one-dimensional arrays of size 5, fill them with random integers from 1 to 10, and perform addition, subtraction, and multiplication operations on them.

In [10]:
a5 = np.random.randint(1, 11, 5)
b5 = np.random.randint(1, 11, 5)

In [11]:
a5, b5, a5+b5, a5-b5, a5*b5

(array([3, 6, 6, 3, 8]),
 array([ 5,  8, 10,  8,  9]),
 array([ 8, 14, 16, 11, 17]),
 array([-2, -2, -4, -5, -1]),
 array([15, 48, 60, 24, 72]))

Create two vectors of size 7, fill them with random numbers, and find their dot product.

In [12]:
a6 = np.random.random(7)
b6 = np.random.random(7)
dot_product_6 = np.dot(a6,b6)

In [13]:
a6,b6,dot_product_6

(array([0.96837379, 0.85608149, 0.44790743, 0.15804017, 0.64726622,
        0.98390118, 0.28951088]),
 array([3.80933001e-01, 8.45497632e-01, 6.24774659e-01, 7.12745246e-01,
        8.11548533e-01, 5.78470601e-01, 6.75190251e-04]),
 2.5798253261562696)

Create two matrices of sizes 2x2 and 2x3, fill them with random integers from 1 to 10, and multiply them.

In [14]:
a7 = np.random.randint(1, 11, (2, 2))
b7 = np.random.randint(1, 11, (2, 3))
multiply_7 = np.dot(a7,b7)


In [15]:
a7,b7,multiply_7

(array([[7, 8],
        [4, 1]]),
 array([[3, 2, 6],
        [6, 9, 6]]),
 array([[69, 86, 90],
        [18, 17, 30]]))

Create a 3x3 matrix, fill it with random integers from 1 to 10, and find its inverse.

In [16]:
a8 = np.random.randint(1, 11, (3, 3))
a8_inv = np.linalg.inv(a8)

In [17]:
a8, a8_inv

(array([[ 8, 10,  2],
        [ 6,  7,  4],
        [ 8,  8,  9]]),
 array([[ 2.58333333, -6.16666667,  2.16666667],
        [-1.83333333,  4.66666667, -1.66666667],
        [-0.66666667,  1.33333333, -0.33333333]]))

Create a 4x4 matrix, fill it with random real numbers from 0 to 1, and transpose it.

In [18]:
a9 = np.random.random((4, 4))
a9_transposed = a9.T

In [19]:
a9,a9_transposed

(array([[0.03372797, 0.29238217, 0.46771593, 0.63790905],
        [0.15333288, 0.74985208, 0.81583057, 0.83721752],
        [0.80599765, 0.89602986, 0.77865872, 0.43844761],
        [0.71292976, 0.30253505, 0.78235344, 0.74719335]]),
 array([[0.03372797, 0.15333288, 0.80599765, 0.71292976],
        [0.29238217, 0.74985208, 0.89602986, 0.30253505],
        [0.46771593, 0.81583057, 0.77865872, 0.78235344],
        [0.63790905, 0.83721752, 0.43844761, 0.74719335]]))

Create a matrix of size 3x4 and a vector of size 4, fill them with random integers from 1 to 10, and multiply the matrix by the vector.

In [20]:
a10 = np.random.randint(1, 11, (3, 4))
b10 = np.random.randint(1, 11, 4)
multiply_10 = np.dot(a10,b10)


In [21]:
a10,b10,multiply_10

(array([[10,  2,  1,  2],
        [ 4,  8,  2,  7],
        [ 8,  2,  1,  6]]),
 array([6, 9, 4, 4]),
 array([ 90, 132,  94]))

Create a matrix of size 2x3 and a vector of size 3, fill them with random real numbers from 0 to 1, and multiply the matrix by the vector.

In [22]:
a11 = np.random.random((2, 3))
b11 = np.random.random(3)
multiply_11 = np.dot(a11,b11)

In [23]:
a11,b11,multiply_11

(array([[0.99097417, 0.11359305, 0.03961785],
        [0.53433831, 0.96681095, 0.89797476]]),
 array([0.01780434, 0.69224039, 0.39267629]),
 array([0.11183432, 1.03139252]))

Create two matrices of size 2x2, fill them with random integers from 1 to 10, and perform element-wise multiplication.

In [24]:
a12 = np.random.randint(1, 11, (2, 2))
b12 = np.random.randint(1, 11, (2, 2))
multiply_12 = a12*b12

In [25]:
a12,b12,multiply_12

(array([[ 8, 10],
        [ 3,  4]]),
 array([[ 8,  3],
        [10,  1]]),
 array([[64, 30],
        [30,  4]]))

Create two matrices of size 2x2, fill them with random integers from 1 to 10, and find their matrix product.

In [26]:
a13 = np.random.randint(1, 11, (2, 2))
b13 = np.random.randint(1, 11, (2, 2))
dot_product_13 = np.dot(a13,b13)

In [27]:
a13,b13,dot_product_13

(array([[9, 1],
        [8, 3]]),
 array([[ 8, 10],
        [ 2,  6]]),
 array([[74, 96],
        [70, 98]]))

Create a 5x5 matrix, fill it with random integers from 1 to 100, and find the sum of matrix elements.

In [28]:
a14 = np.random.randint(1, 101, (5, 5))
sum_14 = np.sum(a14)

In [29]:
a14, sum_14

(array([[30, 32, 73, 38, 65],
        [15, 20,  7, 82, 10],
        [88, 32, 12, 58, 55],
        [ 8, 92, 81, 55, 74],
        [29, 26, 54, 84, 89]]),
 1209)

Create two matrices of size 4x4, fill them with random integers from 1 to 10, and find their difference.

In [30]:
a15 = np.random.randint(1, 11, (4, 4))
b15 = np.random.randint(1, 11, (4, 4))
difference_15 = a15-b15

In [31]:
a15,b15,difference_15

(array([[ 1,  2,  5,  2],
        [ 8,  3,  3,  4],
        [ 4,  5, 10,  7],
        [ 7,  7,  4,  1]]),
 array([[ 6,  3, 10,  4],
        [ 4,  8, 10,  5],
        [ 3,  7,  4,  8],
        [ 3,  5,  3, 10]]),
 array([[-5, -1, -5, -2],
        [ 4, -5, -7, -1],
        [ 1, -2,  6, -1],
        [ 4,  2,  1, -9]]))

Create a 3x3 matrix, fill it with random real numbers from 0 to 1, and find a column vector containing the sum of elements of each row of the matrix.

In [32]:
a16 = np.random.random((3,3))
sum_vector_16 = np.sum(a16,axis=1)

In [33]:
a16,sum_vector_16

(array([[0.48672508, 0.89241525, 0.69748154],
        [0.08231964, 0.36600961, 0.05243578],
        [0.19551614, 0.80963521, 0.28756053]]),
 array([2.07662187, 0.50076502, 1.29271188]))

Create a matrix of size 3x4 with arbitrary integers and create a matrix with the squares of those numbers.

In [34]:
a17 = np.array([[5,1,4,8],
                [1,0,12,31],
                [7,2,3,1],
                [9,2,3,6]])
a17_square = np.square(a17)

In [35]:
a17,a17_square

(array([[ 5,  1,  4,  8],
        [ 1,  0, 12, 31],
        [ 7,  2,  3,  1],
        [ 9,  2,  3,  6]]),
 array([[ 25,   1,  16,  64],
        [  1,   0, 144, 961],
        [ 49,   4,   9,   1],
        [ 81,   4,   9,  36]]))

Create a vector of size 4, fill it with random integers from 1 to 50, and find the vector of square roots of those numbers.

In [36]:
a18 = np.random.randint(1,51,4)
a18_square_root = np.sqrt(a18)

In [37]:
a18,a18_square_root

(array([ 6, 48, 33, 10]),
 array([2.44948974, 6.92820323, 5.74456265, 3.16227766]))